version: "3.3"
services:
  spark-master:
    image: manduca/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/usr/local/spark/sbin/start-master-nondaemon.sh"
  spark-worker:
    image: manduca/spark:latest
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER_HOST=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/usr/local/spark/sbin/start-worker-nondaemon.sh"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
